### ISSUE TITLE
sepolicy syntax error

### ISSUE THREAD

**Issue by Robert3141** [NusantaraROM-Devices/device_xiaomi_sm8250-common#1]
Not sure whether problem with my build enviroment but i get the error:
```
[ 52% 73756/140855] //external/selinux/checkpolicy:checkpolicy link checkpolicy [linux_glibc]
[ 52% 73757/140855] //external/selinux/checkpolicy:checkpolicy install checkpolicy [linux_glibc]
[ 52% 73758/140855] host Prebuilt: checkpolicy (out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/checkpolicy)
[ 52% 73759/140855] Install: out/host/linux-x86/bin/checkpolicy
[ 52% 73760/140855] build out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
FAILED: out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp neverallow -w -f out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/policy_2.conf || 	  ( echo \"\" 1>&2; 	    echo \"sepolicy-analyze failed. This is most likely due to the use\" 1>&2; 	    echo \"of an expanded attribute in a neverallow assertion. Please fix\" 1>&2; 	    echo \"the policy.\" 1>&2; 	    exit 1 ) ) && (touch out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp ) && (mv out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows )"
device/xiaomi/sm8250-common/sepolicy/public/attributes:2:ERROR 'syntax error' at token 'hal_attribute_nad' on line 6611:
#line 1 "device/xiaomi/sm8250-common/sepolicy/public/attributes"
hal_attribute_nad(mlipay)
checkpolicy:  error(s) encountered while parsing configuration
[ 52% 73761/140855] //external/dtc:dtc clang data.c [linux_glibc]
[ 52% 73762/140855] //art/dexoptanalyzer:dexoptanalyzer clang++ dexoptanalyzer.cc [arm apex10000]
[ 52% 73763/140855] //art/dex2oat:dex2oatd clang++ dex2oat_options.cc [linux_glibc]
```
Full build log: 
[pm_04_39.log](https://github.com/NusantaraROM-Devices/device_xiaomi_sm8250-common/files/6415960/pm_04_39.log)

**Comment by goodmeow** [comment]
This error coming from your build env, most likely has '#' sign on compiled sepolicy list and it doesn't happen on apollo

Try adding one blank like or deleting blank line  else.

**Comment by dogpoopy** [comment]
> Not sure whether problem with my build enviroment but i get the error:
> 
> ```
> [ 52% 73756/140855] //external/selinux/checkpolicy:checkpolicy link checkpolicy [linux_glibc]
> [ 52% 73757/140855] //external/selinux/checkpolicy:checkpolicy install checkpolicy [linux_glibc]
> [ 52% 73758/140855] host Prebuilt: checkpolicy (out/host/linux-x86/obj/EXECUTABLES/checkpolicy_intermediates/checkpolicy)
> [ 52% 73759/140855] Install: out/host/linux-x86/bin/checkpolicy
> [ 52% 73760/140855] build out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
> FAILED: out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
> /bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp neverallow -w -f out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/policy_2.conf || 	  ( echo \"\" 1>&2; 	    echo \"sepolicy-analyze failed. This is most likely due to the use\" 1>&2; 	    echo \"of an expanded attribute in a neverallow assertion. Please fix\" 1>&2; 	    echo \"the policy.\" 1>&2; 	    exit 1 ) ) && (touch out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp ) && (mv out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp out/target/product/alioth/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows )"
> device/xiaomi/sm8250-common/sepolicy/public/attributes:2:ERROR 'syntax error' at token 'hal_attribute_nad' on line 6611:
> #line 1 "device/xiaomi/sm8250-common/sepolicy/public/attributes"
> hal_attribute_nad(mlipay)
> checkpolicy:  error(s) encountered while parsing configuration
> [ 52% 73761/140855] //external/dtc:dtc clang data.c [linux_glibc]
> [ 52% 73762/140855] //art/dexoptanalyzer:dexoptanalyzer clang++ dexoptanalyzer.cc [arm apex10000]
> [ 52% 73763/140855] //art/dex2oat:dex2oatd clang++ dex2oat_options.cc [linux_glibc]
> ```
> 
> Full build log: [pm_04_39.log](https://github.com/NusantaraROM-Devices/device_xiaomi_sm8250-common/files/6415960/pm_04_39.log)

Have you ever fixed this issue Sir? If yes please tell me how. I couldn't find enough information about this.

**Comment by goodmeow** [comment]
its fixed by adding sepolicy attributes
